### PR TITLE
`git` is a needed on the OS (or in the path) to clone the repo and run TF with

### PR DESCRIPTION
**Pull request by majormoses**
Call this out in the readme, update test cookbook to reflect, and update tests.

Signed-off-by: Ben Abrams <me@benabrams.it>

#### General

~- [ ] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)~

- [x] Update README with any necessary snippets

- [x] Existing tests pass

#### New Features

- [x] Tests

- [x] Added to the README

#### Purpose
Make atlantis functional

#### Known Compatibility Issues
none

### CODE REVIEW

**Comment by huynt1979** [comment]
Looks good in general. Perhaps semver needs to bump.

**Comment by majormoses** [comment]
It's actually a change only for the testing cookbook if you want we can bump that. Also per our [build and release docs](https://github.com/majormoses/atlantis-chef#build-and-release) we cut versions of the cookbook (technically would not apply to testing cookbook) post acceptance.

**Comment by huynt1979** [comment]
@majormoses let's treat fixture with respect ;)

**Comment by majormoses** [comment]
bumped version of testing cookbook.

**Pull request merged**
